Let's use what we've learned to play a mage duel!

Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.

Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.

Exercises
Simulate mage duels to answer who is the more powerful mage?

Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.
Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?
Do the results change much at 100 duels?
Now, simulate 10,000 mage duels. Is there a clear winner?

In [2]:
import numpy as np
import pandas as pd

np.random.seed(7)

In [16]:
mage1_health = np.random.choice(np.arange(6,24), size = (10_000,1))
mage1_damage = np.random.choice(np.arange(6,24), size = (10_000,1))

#duel = np.random.choice((np.arange(6,24) - np.arange(4,24)))

In [17]:
mage1_health

array([[10],
       [10],
       [14],
       ...,
       [10],
       [ 6],
       [23]])

In [20]:
mage1_health = pd.DataFrame(mage1_health)
mage1_health

0
0     10
1     10
2     14
3     13
4     11
...   ..
9995   7
9996   9
9997  10
9998   6
9999  23

[10000 rows x 1 columns]

In [22]:
mage1_health['mage1_damg'] = mage1_damage
mage1_health

0  mage1_damg
0     10          23
1     10          10
2     14          13
3     13           6
4     11          14
...   ..         ...
9995   7          10
9996   9          18
9997  10           8
9998   6          15
9999  23          21

[10000 rows x 2 columns]

In [24]:
mage2_health = np.random.choice(np.arange(4,24), size = (10_000, 1))
mage2_health

array([[22],
       [14],
       [11],
       ...,
       [11],
       [22],
       [12]])

In [27]:
mage1_health['mage2_hp'] = mage2_health
mage1_health

0  mage1_damg  mage2_hp
0     10          23        22
1     10          10        14
2     14          13        11
3     13           6         4
4     11          14        18
...   ..         ...       ...
9995   7          10         6
9996   9          18         6
9997  10           8        11
9998   6          15        22
9999  23          21        12

[10000 rows x 3 columns]

In [28]:
mage2_damage = np.random.choice(np.arange(4,24), size = (10_000, 1))
mage2_damage

array([[14],
       [21],
       [ 5],
       ...,
       [11],
       [19],
       [12]])

In [29]:
mage1_health['mage2_damg'] = mage2_damage
mage1_health

0  mage1_damg  mage2_hp  mage2_damg
0     10          23        22          14
1     10          10        14          21
2     14          13        11           5
3     13           6         4          14
4     11          14        18          17
...   ..         ...       ...         ...
9995   7          10         6           5
9996   9          18         6          13
9997  10           8        11          11
9998   6          15        22          19
9999  23          21        12          12

[10000 rows x 4 columns]

In [38]:
fire_ball = mage1_health.mage2_hp - mage1_health.mage1_damg
lightning_bolt = mage1_health[0] - mage1_health.mage2_damg


mage1_health['Mage2_after'] = fire_ball
mage1_health['Mage1_after'] = lightning_bolt
mage1_health
#duel = np.random.choice([(lightning_bolt > fire_ball),(lightning_bolt < fire_ball)], size = 10,10)
#duel

0  mage1_damg  mage2_hp  mage2_damg  aftermath1  aftermath2  Winner  \
0     10          23        22          14          -1          -4    True   
1     10          10        14          21           4         -11    True   
2     14          13        11           5          -2           9   False   
3     13           6         4          14          -2          -1   False   
4     11          14        18          17           4          -6    True   
...   ..         ...       ...         ...         ...         ...     ...   
9995   7          10         6           5          -4           2   False   
9996   9          18         6          13         -12          -4   False   
9997  10           8        11          11           3          -1    True   
9998   6          15        22          19           7         -13    True   
9999  23          21        12          12          -9          11   False   

      Mage2_after  Mage1_after  
0              -1           -4  
1               4          -11  
2              -2            9  
3              -2           -1  
4               4           -6  
...           ...          ...  
9995           -4            2  
9996          -12           -4  
9997            3           -1  
9998            7          -13  
9999           -9           11  

[10000 rows x 9 columns]

In [41]:
mage1_health['Winner2'] = mage1_health.Mage2_after > mage1_health.Mage1_after
mage1_health['Mage1_win'] = mage1_health.Mage1_after > mage1_health.Mage2_after

In [42]:
mage1_health

0  mage1_damg  mage2_hp  mage2_damg  aftermath1  aftermath2  Winner  \
0     10          23        22          14          -1          -4    True   
1     10          10        14          21           4         -11    True   
2     14          13        11           5          -2           9   False   
3     13           6         4          14          -2          -1   False   
4     11          14        18          17           4          -6    True   
...   ..         ...       ...         ...         ...         ...     ...   
9995   7          10         6           5          -4           2   False   
9996   9          18         6          13         -12          -4   False   
9997  10           8        11          11           3          -1    True   
9998   6          15        22          19           7         -13    True   
9999  23          21        12          12          -9          11   False   

      Mage2_after  Mage1_after  Winner2  Mage1_win  
0              -1           -4     True      False  
1               4          -11     True      False  
2              -2            9    False       True  
3              -2           -1    False       True  
4               4           -6     True      False  
...           ...          ...      ...        ...  
9995           -4            2    False       True  
9996          -12           -4    False       True  
9997            3           -1     True      False  
9998            7          -13     True      False  
9999           -9           11    False       True  

[10000 rows x 11 columns]

In [43]:
(mage1_health.Mage1_win).mean()

0.5606