In [63]:
import numpy as np
import pandas as pd

np.random.seed(7)

In [ ]:
#How likely is it that you roll doubles when rolling two dice?

In [10]:
n_trials = nrows = 10_000
n_dice = ncols = 2

#die1 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
#die2 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)

die1 = np.random.choice([1, 2, 3, 4, 5, 6], 10_000)
die2 = np.random.choice([1, 2, 3, 4, 5, 6], 10_000)

In [11]:
die1

array([6, 3, 1, ..., 5, 4, 6])

In [12]:
samsies = die1 == die2

In [13]:
samsies

array([ True, False, False, ..., False, False, False])

In [14]:
samsies.mean()

0.17

In [ ]:
#If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?

In [15]:
n_trials = nrows = 10_000
n_coin = ncols = 8
coin = np.random.choice([0, 1], n_trials * n_coin).reshape(nrows, ncols)

coin

array([[0, 0, 1, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 1],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 1, 1],
       [0, 1, 1, ..., 1, 1, 1]])

In [18]:
head_3 = coin.sum(axis=1)
head_3

array([5, 2, 3, ..., 3, 6, 7])

In [19]:
flip_coin = head_3 == 3
flip_coin

array([False, False,  True, ...,  True, False, False])

In [162]:
more_coin = head_3 > 3
more_coin

array([ True, False, False, ..., False,  True,  True])

In [163]:
more_coin.mean()

0.6316

In [20]:
flip_coin.mean()

0.2192

In [21]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, 
# what are the odds that the two billboards I drive past both have data science students on them?

In [36]:
n_trials = nrows = 10_000
n_billboard = ncols = 2

cohorts = np.random.choice(["Web", "Web", "Web", "Data"], n_trials * n_billboard).reshape(nrows, ncols)
cohorts

array([['Web', 'Web'],
       ['Web', 'Web'],
       ['Data', 'Data'],
       ...,
       ['Web', 'Web'],
       ['Web', 'Web'],
       ['Data', 'Web']], dtype='<U4')

In [37]:
cohorts = pd.DataFrame(cohorts, columns=["billboard_1", "billboard_2"])
cohorts.head()

billboard_1 billboard_2
0         Web         Web
1         Web         Web
2        Data        Data
3        Data         Web
4         Web         Web

In [44]:
def count_data(row):
    return row.billboard_1.count("Data") + row.billboard_2.count("Data")

In [47]:
cohorts["Data_counts"] = cohorts.apply(count_web, axis=1)
cohorts

billboard_1 billboard_2  Web_Counts  Data_counts
0            Web         Web           0            0
1            Web         Web           0            0
2           Data        Data           2            2
3           Data         Web           1            1
4            Web         Web           0            0
...          ...         ...         ...          ...
9995         Web         Web           0            0
9996        Data         Web           1            1
9997         Web         Web           0            0
9998         Web         Web           0            0
9999        Data         Web           1            1

[10000 rows x 4 columns]

In [48]:
(cohorts.Data_counts == 2).mean()

0.0629

In [49]:
# Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5
# a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, 
# how likely is it that I will be able to buy some poptarts on Friday afternoon? 
# (Remember, if you have mean and standard deviation, use the np.random.normal)

In [55]:
mean = 3
std = 1.5

n_trials = 10_000
n_days = 5


students = np.random.normal(mean, std, size = (n_trials, n_days, ))
students = pd.DataFrame(students)
students

0         1         2         3         4
0     5.539810  2.254008  0.361692  3.813584  0.713407
1     7.090607  3.474223  4.255589  1.284212  3.295398
2     4.090645  2.565645  4.943593  4.874376  5.263110
3     6.907632  1.340947  0.949638  3.175718  4.955617
4     0.388626  0.747842  2.843280  3.485616  2.380095
...        ...       ...       ...       ...       ...
9995  4.747012  1.302705  6.742289  3.516151  2.446843
9996  0.985244  4.580780  4.206978  4.103466  1.748775
9997  2.356705  4.206803  3.441644  3.258140  0.200288
9998  2.752135  0.753780  6.604477  4.345175  3.594965
9999  2.333649  3.650210  5.042631  2.067433  3.590186

[10000 rows x 5 columns]

In [56]:
students["n_poptarts"] = students.sum(axis=1)
students

0         1         2         3         4  n_poptarts
0     5.539810  2.254008  0.361692  3.813584  0.713407   12.682501
1     7.090607  3.474223  4.255589  1.284212  3.295398   19.400029
2     4.090645  2.565645  4.943593  4.874376  5.263110   21.737370
3     6.907632  1.340947  0.949638  3.175718  4.955617   17.329552
4     0.388626  0.747842  2.843280  3.485616  2.380095    9.845458
...        ...       ...       ...       ...       ...         ...
9995  4.747012  1.302705  6.742289  3.516151  2.446843   18.755001
9996  0.985244  4.580780  4.206978  4.103466  1.748775   15.625243
9997  2.356705  4.206803  3.441644  3.258140  0.200288   13.463580
9998  2.752135  0.753780  6.604477  4.345175  3.594965   18.050533
9999  2.333649  3.650210  5.042631  2.067433  3.590186   16.684109

[10000 rows x 6 columns]

In [57]:
(students.n_poptarts < 17).mean()

0.727

In [58]:
#
#Compare Heights

#Men have an average height of 178 cm and standard deviation of 8cm.
#Women have a mean of 170, sd = 6cm.
#Since you have means and standard deviations, you can use np.random.normal to generate observations.
#If a man and woman are chosen at random, P(woman taller than man)?

In [66]:
mean_men = 178
std_men = 8

mean_women = 170
std_women = 6

men = np.random.normal(mean_men, std_men, 10_000)
women = women = np.random.normal(mean_women, std_women, 10_000)

(women > men).mean()

0.2145

In [68]:
# When installing anaconda on a student's computer, there's a 1 in 250 chance that the 
# download is corrupted and the installation fails. 
# What are the odds that after having 50 students download anaconda, 
# no one has an installation issue? 100 students?

In [69]:
1/250

0.004

In [83]:
install = np.random.choice([0, 1], size= 50, p=[0.004, 0.996])

(install == 0).mean()

0.0

In [82]:
install2 = np.random.choice([0, 1], size= 100, p=[0.004, 0.996])

(install2 == 0).mean()

0.0

In [ ]:
# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [84]:
install3 = np.random.choice([0, 1], size= 150, p=[0.004, 0.996])

(install3 == 0).mean()

0.006666666666666667

In [ ]:
#How likely is it that 450 students all download anaconda without an issue?

In [76]:
install4 = np.random.choice([0, 1], size= 450, p=[0.004, 0.996])

(install4 == 0).mean()

0.0044444444444444444

In [77]:
# There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?



In [117]:
n_trials = nrows = 10_000
n_dats = ncols = 5


foodtruck = np.random.choice([0,1], n_trials * n_days, p=[.3, .7]).reshape(nrows, ncols)
foodtruck

array([[1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [0, 0, 1, 1, 1],
       ...,
       [1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 1]])

In [118]:
foodtrucks = pd.DataFrame(foodtruck)
foodtrucks.head()

0  1  2  3  4
0  1  1  1  1  1
1  1  0  1  1  1
2  0  0  1  1  1
3  0  0  0  1  1
4  1  0  1  1  1

In [120]:
foodtrucks.iloc[ : , :3]

0  1  2
0     1  1  1
1     1  0  1
2     0  0  1
3     0  0  0
4     1  0  1
...  .. .. ..
9995  1  1  1
9996  1  1  1
9997  1  0  1
9998  1  0  1
9999  0  1  0

[10000 rows x 3 columns]

In [122]:
foodtrucks["no_show"] = foodtrucks.iloc[ : , :3].sum(axis=1)
foodtrucks

0  1  2  3  4  no_show
0     1  1  1  1  1        3
1     1  0  1  1  1        2
2     0  0  1  1  1        1
3     0  0  0  1  1        0
4     1  0  1  1  1        2
...  .. .. .. .. ..      ...
9995  1  1  1  1  0        3
9996  1  1  1  1  1        3
9997  1  0  1  0  1        2
9998  1  0  1  0  1        2
9999  0  1  0  1  1        1

[10000 rows x 6 columns]

In [123]:
(foodtrucks.no_show == 0).mean()

0.0261

In [ ]:
# How likely is it that a food truck will show up sometime this week?

In [126]:
foodtrucks.iloc[ : , 3:5]

3  4
0     1  1
1     1  1
2     1  1
3     1  1
4     1  1
...  .. ..
9995  1  0
9996  1  1
9997  0  1
9998  0  1
9999  1  1

[10000 rows x 2 columns]

In [127]:
foodtrucks["last_two_days"] = foodtrucks.iloc[ : , 3:5].sum(axis=1)
foodtrucks

0  1  2  3  4  no_show  last_two_days
0     1  1  1  1  1        3              2
1     1  0  1  1  1        2              2
2     0  0  1  1  1        1              2
3     0  0  0  1  1        0              2
4     1  0  1  1  1        2              2
...  .. .. .. .. ..      ...            ...
9995  1  1  1  1  0        3              1
9996  1  1  1  1  1        3              2
9997  1  0  1  0  1        2              1
9998  1  0  1  0  1        2              1
9999  0  1  0  1  1        1              2

[10000 rows x 7 columns]

In [128]:
(foodtrucks.last_two_days != 0).mean()

0.9162

In [103]:
# If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?

In [138]:
n_samsies = n_col = 2
n_people = n_rows = 23

In [140]:
probabilty = 1/365
probabilty

0.0027397260273972603

In [130]:
(1/365) * (1/365)

7.5060987051979735e-06

In [158]:
birthday1 = np.random.choice(np.arange(0,366), size = (100_000, 23))
birthday1

array([[192, 315,  81, ..., 201, 250, 221],
       [141,  69,   6, ...,  12, 181, 201],
       [ 63,  91, 269, ..., 137, 154, 271],
       ...,
       [113, 201, 259, ...,  96, 338, 129],
       [220, 150, 227, ...,  79, 273, 193],
       [116,  83, 186, ...,  59, 138, 256]])

In [159]:
birthdays = pd.DataFrame(birthday1)
birthdays

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      192  315   81  101  345   57   36  183  324  365  ...  252   29   63   
1      141   69    6   83  294  208  275  129  250  154  ...   10  130  165   
2       63   91  269   89  196  166   45  240  295  304  ...   27   58  296   
3      178   73  160  198   87   55  338  329    3  328  ...   20  138  138   
4       29  327  113  132  293  140  316  118  212  134  ...  294  273   67   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  103  236    3  159  214  245  179  335  202   87  ...  111  278  364   
99996  120    1  134  192   22    3  141  330  198  270  ...  229   33  279   
99997  113  201  259  128  157   85  114   48  289  148  ...  310  110   27   
99998  220  150  227   11  180  212  189   77   99   62  ...   36   46  355   
99999  116   83  186  123  157  142  222  301  245  333  ...   81  184  167   

        16   17   18   19   20   21   22  
0       23   95   64  247  201  250  221  
1      175  154  232  337   12  181  201  
2      311  345   83  362  137  154  271  
3       64   84  305  355   34  121  151  
4      163   99  307  182  299  365  294  
...    ...  ...  ...  ...  ...  ...  ...  
99995  216  175  146  234  223  225  146  
99996   28  160  121  231  126  116   64  
99997  277  147  281  166   96  338  129  
99998  329  297  102  316   79  273  193  
99999  304  318   91  297   59  138  256  

[100000 rows x 23 columns]

In [160]:
birthdays["unique_birthdays"] = birthdays.nunique(axis = 1)
birthdays

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0      192  315   81  101  345   57   36  183  324  365  ...   29   63   23   
1      141   69    6   83  294  208  275  129  250  154  ...  130  165  175   
2       63   91  269   89  196  166   45  240  295  304  ...   58  296  311   
3      178   73  160  198   87   55  338  329    3  328  ...  138  138   64   
4       29  327  113  132  293  140  316  118  212  134  ...  273   67  163   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  103  236    3  159  214  245  179  335  202   87  ...  278  364  216   
99996  120    1  134  192   22    3  141  330  198  270  ...   33  279   28   
99997  113  201  259  128  157   85  114   48  289  148  ...  110   27  277   
99998  220  150  227   11  180  212  189   77   99   62  ...   46  355  329   
99999  116   83  186  123  157  142  222  301  245  333  ...  184  167  304   

        17   18   19   20   21   22  unique_birthdays  
0       95   64  247  201  250  221                23  
1      154  232  337   12  181  201                22  
2      345   83  362  137  154  271                22  
3       84  305  355   34  121  151                21  
4       99  307  182  299  365  294                22  
...    ...  ...  ...  ...  ...  ...               ...  
99995  175  146  234  223  225  146                22  
99996  160  121  231  126  116   64                23  
99997  147  281  166   96  338  129                23  
99998  297  102  316   79  273  193                23  
99999  318   91  297   59  138  256                23  

[100000 rows x 24 columns]

In [161]:
(birthdays.unique_birthdays < 23).mean()

0.50669

In [154]:
birthday2 = np.random.choice(np.arange(0,366), size = (10_000, 20))


birthdays2 = pd.DataFrame(birthday2)


birthdays2["unique_birthdays"] = birthdays2.nunique(axis = 1)
birthdays2

0    1    2    3    4    5    6    7    8    9  ...   11   12   13  \
0     275   66   64  145   22  331  334   15  264  158  ...   16  155  189   
1     154    7  253  175   65  289   50   91  353  362  ...  197  149  267   
2      35  295  151  132  363  108  111  354  363  289  ...  330  123  321   
3      68  148  215  341   99  294  201  229   28  180  ...  283  243  267   
4       6  364  133  218  172  272  278  231  252  225  ...  126  114  325   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  215   53  227    7  201  114  199  297  206  267  ...  362   92  237   
9996   15  228   59  165  252  116  182  103   89  186  ...  184  224   93   
9997  112  134   63  119   45   51  142  218  222   63  ...  144  228  169   
9998  281  187  236  276  233  183  317   86   16  131  ...  349  351   29   
9999   79  305  323   96  354  185  183   81  347  114  ...  168    6  304   

       14   15   16   17   18   19  unique_birthdays  
0     111   45  307  363  291  193                20  
1     131  329   54   14  173  245                20  
2     238  327  191  193  102   42                19  
3      35  311  236  193  137  113                20  
4     346  169  114   13   64  172                18  
...   ...  ...  ...  ...  ...  ...               ...  
9995  145   18  188  268   86   74                20  
9996  284   40   57   29  187  141                20  
9997   76   10  332  299   47   17                19  
9998  242  247  349  194  138  204                19  
9999  224  118  210  357  216   25                20  

[10000 rows x 21 columns]

In [155]:
(birthdays2.unique_birthdays < 20).mean()

0.4177

In [156]:
birthday3 = np.random.choice(np.arange(0,366), size = (10_000, 40))


birthdays3 = pd.DataFrame(birthday3)


birthdays3["unique_birthdays"] = birthdays3.nunique(axis = 1)
birthdays3

0    1    2    3    4    5    6    7    8    9  ...   31   32   33  \
0      62  178  248  343   49  290   47   14   76  267  ...   76   91   23   
1     127   96  294  145   54  352  287  351   27  107  ...  113  308   33   
2     323  258  112  228   30  201   13  333   59  149  ...   62  214  255   
3     211  163  130   79  194   73   63  360  205   36  ...  172  355  303   
4     348  291  277  123   95  213  153  199   99  133  ...  322   53  244   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995    5  238  118  164  134  246  355   34  162  317  ...   32  206  261   
9996  181  235   45   32  235  259    5  138  299  271  ...   47  247   21   
9997  178  268  276  190  104  304  287  201   35  288  ...   75  134   12   
9998  261  317  105   62  315  206  301   62  315   42  ...  182  176  356   
9999   31  262  183  356  186  224  189  297  106   26  ...  266   27  161   

       34   35   36   37   38   39  unique_birthdays  
0      15  198  304  205  144  231                37  
1     203  288  325  169   63  292                40  
2     104   32  135  166  363  179                38  
3     160   90  228  254  189  158                38  
4     209  297   97  233  349  178                35  
...   ...  ...  ...  ...  ...  ...               ...  
9995   39  136   95  220  337  298                37  
9996   43  145  269    1  272  343                38  
9997  115  125  254   64  336   72                36  
9998  165    4   12  239   38   54                35  
9999   81  277  338  363  207   54                38  

[10000 rows x 41 columns]

In [157]:
(birthdays2.unique_birthdays < 40).mean()

1.0