In [ ]:
How likely is it that you roll doubles when rolling two dice?









In [63]:
import numpy as np
import pandas as pd

np.random.seed(7)

In [10]:
n_trials = nrows = 10_000
n_dice = ncols = 2

#die1 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
#die2 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)

die1 = np.random.choice([1, 2, 3, 4, 5, 6], 10_000)
die2 = np.random.choice([1, 2, 3, 4, 5, 6], 10_000)

In [11]:
die1

array([6, 3, 1, ..., 5, 4, 6])

In [12]:
samsies = die1 == die2

In [13]:
samsies

array([ True, False, False, ..., False, False, False])

In [14]:
samsies.mean()

0.17

In [ ]:
#If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?

In [15]:
n_trials = nrows = 10_000
n_coin = ncols = 8
coin = np.random.choice([0, 1], n_trials * n_coin).reshape(nrows, ncols)

coin

array([[0, 0, 1, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 1],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 1, 1],
       [0, 1, 1, ..., 1, 1, 1]])

In [18]:
head_3 = coin.sum(axis=1)
head_3

array([5, 2, 3, ..., 3, 6, 7])

In [19]:
flip_coin = head_3 == 3
flip_coin

array([False, False,  True, ...,  True, False, False])

In [20]:
flip_coin.mean()

0.2192

In [21]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, 
# what are the odds that the two billboards I drive past both have data science students on them?

In [36]:
n_trials = nrows = 10_000
n_billboard = ncols = 2

cohorts = np.random.choice(["Web", "Web", "Web", "Data"], n_trials * n_billboard).reshape(nrows, ncols)
cohorts

array([['Web', 'Web'],
       ['Web', 'Web'],
       ['Data', 'Data'],
       ...,
       ['Web', 'Web'],
       ['Web', 'Web'],
       ['Data', 'Web']], dtype='<U4')

In [37]:
cohorts = pd.DataFrame(cohorts, columns=["billboard_1", "billboard_2"])
cohorts.head()

billboard_1 billboard_2
0         Web         Web
1         Web         Web
2        Data        Data
3        Data         Web
4         Web         Web

In [44]:
def count_data(row):
    return row.billboard_1.count("Data") + row.billboard_2.count("Data")

In [47]:
cohorts["Data_counts"] = cohorts.apply(count_web, axis=1)
cohorts

billboard_1 billboard_2  Web_Counts  Data_counts
0            Web         Web           0            0
1            Web         Web           0            0
2           Data        Data           2            2
3           Data         Web           1            1
4            Web         Web           0            0
...          ...         ...         ...          ...
9995         Web         Web           0            0
9996        Data         Web           1            1
9997         Web         Web           0            0
9998         Web         Web           0            0
9999        Data         Web           1            1

[10000 rows x 4 columns]

In [48]:
(cohorts.Data_counts == 2).mean()

0.0629

In [49]:
# Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5
# a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, 
# how likely is it that I will be able to buy some poptarts on Friday afternoon? 
# (Remember, if you have mean and standard deviation, use the np.random.normal)

In [55]:
mean = 3
std = 1.5

n_trials = 10_000
n_days = 5


students = np.random.normal(mean, std, size = (n_trials, n_days, ))
students = pd.DataFrame(students)
students

0         1         2         3         4
0     5.539810  2.254008  0.361692  3.813584  0.713407
1     7.090607  3.474223  4.255589  1.284212  3.295398
2     4.090645  2.565645  4.943593  4.874376  5.263110
3     6.907632  1.340947  0.949638  3.175718  4.955617
4     0.388626  0.747842  2.843280  3.485616  2.380095
...        ...       ...       ...       ...       ...
9995  4.747012  1.302705  6.742289  3.516151  2.446843
9996  0.985244  4.580780  4.206978  4.103466  1.748775
9997  2.356705  4.206803  3.441644  3.258140  0.200288
9998  2.752135  0.753780  6.604477  4.345175  3.594965
9999  2.333649  3.650210  5.042631  2.067433  3.590186

[10000 rows x 5 columns]

In [56]:
students["n_poptarts"] = students.sum(axis=1)
students

0         1         2         3         4  n_poptarts
0     5.539810  2.254008  0.361692  3.813584  0.713407   12.682501
1     7.090607  3.474223  4.255589  1.284212  3.295398   19.400029
2     4.090645  2.565645  4.943593  4.874376  5.263110   21.737370
3     6.907632  1.340947  0.949638  3.175718  4.955617   17.329552
4     0.388626  0.747842  2.843280  3.485616  2.380095    9.845458
...        ...       ...       ...       ...       ...         ...
9995  4.747012  1.302705  6.742289  3.516151  2.446843   18.755001
9996  0.985244  4.580780  4.206978  4.103466  1.748775   15.625243
9997  2.356705  4.206803  3.441644  3.258140  0.200288   13.463580
9998  2.752135  0.753780  6.604477  4.345175  3.594965   18.050533
9999  2.333649  3.650210  5.042631  2.067433  3.590186   16.684109

[10000 rows x 6 columns]

In [57]:
(students.n_poptarts < 17).mean()

0.727

In [58]:
#
#Compare Heights

#Men have an average height of 178 cm and standard deviation of 8cm.
#Women have a mean of 170, sd = 6cm.
#Since you have means and standard deviations, you can use np.random.normal to generate observations.
#If a man and woman are chosen at random, P(woman taller than man)?

In [66]:
mean_men = 178
std_men = 8

mean_women = 170
std_women = 6

men = np.random.normal(mean_men, std_men, 10_000)
women = women = np.random.normal(mean_women, std_women, 10_000)

(women > men).mean()

0.2145

In [68]:
# When installing anaconda on a student's computer, there's a 1 in 250 chance that the 
# download is corrupted and the installation fails. 
# What are the odds that after having 50 students download anaconda, 
# no one has an installation issue? 100 students?

In [69]:
1/250

0.004

In [83]:
install = np.random.choice([0, 1], size= 50, p=[0.004, 0.996])

(install == 0).mean()

0.0

In [82]:
install2 = np.random.choice([0, 1], size= 100, p=[0.004, 0.996])

(install2 == 0).mean()

0.0

In [ ]:
# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [84]:
install3 = np.random.choice([0, 1], size= 150, p=[0.004, 0.996])

(install3 == 0).mean()

0.006666666666666667

In [ ]:
#How likely is it that 450 students all download anaconda without an issue?

In [76]:
install4 = np.random.choice([0, 1], size= 450, p=[0.004, 0.996])

(install4 == 0).mean()

0.0044444444444444444

In [77]:
# There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?

# How likely is it that a food truck will show up sometime this week?

In [97]:
n_trials = nrows = 10_000
n_dats = ncols = 5


foodtruck = np.random.choice([0,1], n_trials * n_days, p=[.3, .7]).reshape(nrows, ncols)
foodtruck

array([[0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1],
       ...,
       [1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1]])

In [104]:
foodtrucks = pd.DataFrame(foodtruck)
foodtrucks.head()

0  1  2  3  4
0  0  1  1  1  0
1  1  0  1  1  0
2  1  0  1  1  1
3  0  0  0  1  1
4  1  0  0  1  1

In [108]:
((foodtrucks[:2]).sum() == 0).mean()

0.2

In [101]:
foodday = foodtruck.sum(axis=1)
foodday

array([3, 3, 4, ..., 5, 3, 4])

In [109]:
(foodday == 3).mean()

0.3129

In [103]:
# If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?